// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AjoutmodifsupprTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ajoutmodifsuppr() {
    driver.get("http://localhost:8888/TP2/");
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("TestToto");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("test.toto@gmail.com");
    driver.findElement(By.cssSelector("button")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("button:nth-child(1)")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("TestTotoModifE2E");
    driver.findElement(By.cssSelector("button:nth-child(4)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("button:nth-child(2)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("li"));
      assert(elements.size() == 0);
    }
  }
}
